#!/bin/zsh

local file=$1
local ag_opts=(
	--hidden
	--ignore-dir=.git
	--color
#	--context=2
	--heading
)

for arg in "$@"; do
	if [[ "$arg" == -- ]]; then
		shift
		break
	elif [[ "$arg" == -* ]]; then
		ag_opts+=("$arg")
		shift
	fi
done

if [[ $# -eq 1 || ! -e "$file" ]]; then
	ag_opts+=("$*")
else
	shift
	ag_opts+=("$*" "$file")
fi

if [[ -t 1 ]]; then
	ag "${ag_opts[@]}" | less
else
	ag "${ag_opts[@]}"
fi
