#!/bin/zsh

local since
local remaining_args=()
for arg in "$@"; do
    shift
    if [[ "$arg" =~ ^[^-] ]]; then
        since=--since="$arg"
        break
    fi
    remaining_args+=("$arg")
done
git log \
    --oneline \
    --graph \
    --decorate=full \
    $since \
    "${remaining_args[@]}" \
    "$@"
