#!/usr/bin/env zsh

setopt LOCAL_OPTIONS NO_MONITOR

local timeout_seconds=$1; shift
local command_args=("$@")

{ sleep "$timeout_seconds" && kill "$command_pid" && return 1 } &
local sleep_command_pid=$!

"${command_args[@]}"
rc=$?
kill "$sleep_command_pid" &>/dev/null
wait "$sleep_command_pid"
return "$rc"
