#!/bin/zsh

# Find your version by running `pip --version`
local versions=(
	2.7
	3.{5..9}
)
for (( i=${#versions}; i >= 0; i-- )); do
	version=${versions[i]}
	for lib in {/usr/local,/opt/homebrew}/lib/python${version}/{site,dist}-packages; do
		if [[ -d "$lib" ]]; then
			export PYTHON_LIB="$lib"
			return
		fi
	done
	for lib in ~/Library/Python/${version}/lib/python/site-packages; do
		if [[ -d "$lib" ]]; then
			export PYTHON_LIB="$lib"
			export PATH=$(realpath "$lib"/../../../bin):$PATH
			return
		fi
	done
done

return 1
