#!/usr/bin/env bash

alias dc=docker-compose
alias dm=docker-machine
alias dsls="docker service ls --format 'table {{.Name}}\t{{.Mode}}\t{{.Replicas}}\t{{.Ports}}'"
alias gb="git branch --format='%(authordate:short) %(color:red)%(objectname:short) %(color:yellow)%(refname:short)%(color:reset) (%(color:green)%(committerdate:relative)%(color:reset))'"
alias gc='git checkout'
alias gcb='git checkout -b'
alias gcd='git checkout develop'
alias gcm='git checkout "$(git_default_branch)"'
alias gd='git diff'
alias gdm='git diff origin/$(git_default_branch)'
alias git-word-diff='git diff --word-diff --color-words="[^[:space:],()<>]+|[[:space:],()<>]+/s"'
if macos || linux; then
    alias git='git -c delta.light="$(background-color-dark && echo false || echo true)"'
else
    alias gd=git-word-diff
fi
alias gdiff=gd
alias gds='gd --staged'
alias gf='git pull --ff-only'
alias gitff=gf
alias glt='go test $(glide novendor)'
alias grep='grep --color=auto'
alias gs='git status'
alias ic='ibmcloud'
alias kc=kubectl
alias le='logentry'
alias less='less -r'
alias ls='ls -G'
alias ncdu='ncdu --color=dark'
alias sftp='sftp -C -R 1024 -B 1048576'
alias venv3='source ~/bin/mypip3/bin/activate'
alias venv='source ~/bin/mypip/bin/activate'
alias watch='watch -c -d -n5'
alias :q="echo \"This isn't Vim!\""
