#!/bin/sh

if [[ -z "$DOTFILES_DIR" ]]; then
    echo 'Error: $DOTFILES_DIR is not set' >&2
    exit 2
fi

dotenv() {
    src=$1
    if [[ ! -e "$src" ]]; then
        src="$DOTFILES_DIR/$src"
    fi
    if [[ -z "$src" ]]; then
        echo 'Usage: dotenv env_src'
        return 2
    fi
    if [[ ! -e "$src" ]]; then
        echo "Env file not found: $src"
        return 1
    fi
    set -a
    source "$src"
    set +a
}

dotsecrets() {
    if [[ -f "$DOTFILES_DIR"/shell/secrets ]]; then
        dotenv shell/secrets
    fi
    if [[ -f "$HOME"/.dotfiles.secrets ]]; then
        dotenv ~/.dotfiles.secrets
    fi
}

# Adapted from https://stackoverflow.com/a/3915420/1530494
# Since this should be /bin/sh compatible, only backticks are used.
realpath() {
    src=$1
    dir=`dirname "$src"`
    base=`basename "$src"`
    echo -n "`cd "$dir" && pwd`/$base"
}

lazyfunc_apply() {
    func_name=$1; shift
    func_src=`realpath "$1"`; shift
    eval "$func_name() {
        `cat "$func_src"`
    }"
    "$func_name" "$@"
}

lazyfunc() {
    func_name=$1
    func_src=$2
    if [[ -z "$func_name" || -z "$func_src" ]]; then
        echo 'Usage: lazyfunc func_name func_src' >&2
        return 2
    fi
    if [[ ! -e "$func_src" ]]; then
        echo "lazyfunc: Function source does not exist: '$func_src'" >&2
        return 1
    fi
    eval \
    "$func_name"'() {
        '"lazyfunc_apply '$func_name' '$func_src'"' "$@"
    }'
}

lazyfunc_dir() {
    dir=$1
    if [[ -z "$dir" || ! -d "$dir" ]]; then
        echo 'Usage: lazyfunc_dir FUNCTION_DIRECTORY' >&2
        return 2
    fi
    for func_file in "$dir"/*; do
        func_name=`basename "$func_file"`
        if [[ ! -d "$func_file" ]]; then
            lazyfunc "$func_name" "$func_file"
        fi
    done
}

# Update dotfiles repo and re-run the installer
dotupdate() {
    (cd ~/.dotfiles && git pull --ff-only origin master)
    rc=$?
    if [[ $rc -ne 0 ]]; then
        return $rc
    fi
    ~/.dotfiles/install.sh
}

# with_uname detects if the platform matches $1. If so, returns true.
# If additional args are provided, it runs them as a command.
# NOTE: Caches the uname globally.
_dotfiles_uname=
function with_uname() {
    local match=$1
    shift
    local args=$@
    if [[ -z "$_dotfiles_uname" ]]; then
        _dotfiles_uname=$(uname)
    fi
    if [[ "$_dotfiles_uname" == "$match" ]]; then
        if [[ ! -z "${args[*]}" ]]; then
            eval "${args[@]}"
            return $?
        else
            return 0
        fi
    fi
    return 1
}

function macos() {
    with_uname Darwin "$@"
}

function linux() {
    with_uname Linux "$@"
}

function python_lib() {
    # Find your version by running `pip --version`
    local versions=(
        2.7
        3.{5..30}
    )
    for version in "${versions[@]}"; do
        for lib in {~/.local,/usr/local,/opt/homebrew}/lib/python${version}/{site,dist}-packages; do
            if [[ -d "$lib" ]]; then
                export PYTHON_LIB="$lib"
                return
            fi
        done
        for lib in ~/Library/Python/${version}/lib/python/site-packages; do
            if [[ -d "$lib" ]]; then
                export PYTHON_LIB="$lib"
                export PATH=$(realpath "$lib"/../../../bin):$PATH
                return
            fi
        done
    done
    return 1
}
