#!/bin/zsh

# Z Shell profiler
#zmodload zsh/zprof

# Antigen ZSH package manager
ANTIGEN_REPO_PATH="$HOME"/.antigen/bundles/zsh-users/antigen
if [[ ! -d "$ANTIGEN_REPO_PATH" ]]; then
	mkdir -p "$HOME"/.antigen/bundles/zsh-users/antigen
	git clone https://github.com/zsh-users/antigen.git "$ANTIGEN_REPO_PATH"
fi

source "$ANTIGEN_REPO_PATH"/antigen.zsh
antigen init "$HOME"/.antigenrc

# Complete brew stuff
fpath=(/usr/local/share/zsh-completions "${fpath[@]}")

DOTFILES_DIR=~/.dotfiles
source "$DOTFILES_DIR/shell/functions"
dotsecrets
dotenv shell/env
dotenv shell/aliases

# Custom autoload functions
ZSH_MODULES_DIR="$DOTFILES_DIR"/zsh/modules
fpath=("$ZSH_MODULES_DIR" "${fpath[@]}")
autoload -Uz $(ls "$ZSH_MODULES_DIR" | grep -v '\.zwc$')

# Machine-specific custom autoload functions
if [[ -d ~/bin/zsh ]]; then
    fpath=(~/bin/zsh "${fpath[@]}")
    autoload -Uz $(ls ~/bin/zsh | grep -v '\.zwc')
fi

# Set PYTHON_LIB to appropriate location
python_lib
