#!/bin/zsh

# Z Shell profiler
#zmodload zsh/zprof

# Antigen ZSH package manager
ANTIGEN_REPO_PATH="$HOME"/.antigen/bundles/zsh-users/antigen
if [[ ! -d "$ANTIGEN_REPO_PATH" ]]; then
	mkdir -p "$HOME"/.antigen/bundles/zsh-users/antigen
	git clone https://github.com/zsh-users/antigen.git "$ANTIGEN_REPO_PATH"
fi

source "$ANTIGEN_REPO_PATH"/antigen.zsh
antigen init "$HOME"/.antigenrc
# Disable line rewriting via syntax highlighting when on a remote connection
if [[ -z "$SSH_TTY" && -z "$SSH_CLIENT" ]]; then
    ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
else
    ZSH_HIGHLIGHT_HIGHLIGHTERS=()
fi

# Complete brew stuff
fpath=(/usr/local/share/zsh-completions "${fpath[@]}")

# Set history options
setopt hist_ignore_all_dups
setopt hist_reduce_blanks
HISTSIZE=10000000
SAVEHIST=10000000

# Prompt customization
autoload -Uz colors && colors
js_ret_prompt="%(?:%{${fg[green]}%}➜:%{${fg[red]}%}➜)"
PROMPT='${js_ret_prompt} $(js_host_prompt)%{$fg_bold[cyan]%}%c%{$reset_color%} $(js_kubectl_prompt)$(js_docker_prompt)${js_git_prompt}'

dotenv shell/aliases

# Custom autoload functions
ZSH_MODULES_DIR="$DOTFILES_DIR"/zsh/modules
fpath=("$ZSH_MODULES_DIR" "${fpath[@]}")
autoload -Uz $(ls "$ZSH_MODULES_DIR" | grep -v '\.zwc$')

# Machine-specific custom autoload functions
if [[ -d ~/bin/zsh ]]; then
    fpath=(~/bin/zsh "${fpath[@]}")
    autoload -Uz $(ls ~/bin/zsh | grep -v '\.zwc')
fi

# Set PYTHON_LIB to appropriate location
python_lib

REPORTTIME=10
