#!/bin/bash

# Use dotfiles to set up
DOTFILES_DIR=~/.dotfiles
source "$DOTFILES_DIR/shell/functions"
dotsecrets
dotenv shell/env
dotenv shell/aliases
dotenv bash/env

shopt -s nullglob

export BASH_PROMPT_PREFIX=''
export BASH_PROMPT_POSTFIX=''
export BASH_PROMPT="${USER/johnstarich/js}@${HOSTNAME:0:9}:\W\$ "
export MODULES=()

if [ -d ~/.bash_modules ]; then
	for module in ~/.bash_modules/*/index.sh; do
		echo -ne "\033[31m"
		source "$module"
		rc=$?
		echo -ne "\033[0;00m"
		module="${module/$HOME\/.bash_modules\//}"
		module="${module/\/index.sh/}"
		if [[ $rc != 0 ]]; then
			echo "Error loading module: $module"
		else
			MODULES+=("$module")
		fi
	done

	lazyfunc_dir ~/.bash_modules/bin

	if [[ "$SHELL" == *bash* ]]; then
		OLD_PS1=${PS1}
		if [[ ! -z "$BASH_PROMPT" ]]; then
			PS1=$BASH_PROMPT
		fi
		if [[ ! -z "$BASH_PROMPT_PREFIX" ]]; then
			PS1=${BASH_PROMPT_PREFIX}$PS1
		fi
		if [[ ! -z "$BASH_PROMPT_POSTFIX" ]]; then
			PS1+=$BASH_PROMPT_POSTFIX
		fi
	fi
fi

function modules {
	echo "Loaded modules:"
	for module in "${MODULES[@]}"; do
		echo " - $module"
	done
}

